config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "toppage#index"
  resources :toppage, only:[:index,:show]
  resources :cat, only:[:index,:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  belongs_to :cat
end

app/models/cat.rb
class Cat < ApplicationRecord
  has_many :photo
  has_many :user
  has_many :like
  has_many :area
  belongs_to :color
  
end

app/models/color.rb
class Color < ApplicationRecord
  belongs_to :cat
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :cat
  belongs_to :user
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  belongs_to :cat
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cats
  has_many :comment
  has_many :photo
  has_many :like
  belongs_to :cat
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cat_controller.rb
class CatController < ApplicationController
  def index
  end
end

app/controllers/toppage_controller.rb
class ToppageController < ApplicationController
  def index
  end

  def show 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_helper.rb
module CatHelper
end

app/helpers/toppage_helper.rb
module ToppageHelper
end

app/views/cat/index.html.haml
.ranking
  %h1.text10 いいね！ランキング
  .ranking__contents
    .ranking__contents--text
      %h1.no1 No.1
    .ranking__contents--contents_box
      = link_to "#"
      .ranking__contents--contents_box--image
        = image_tag 'top_cat.jpg',height: '100', width: '100',class:"mini_image"
      .ranking__contents--contents_box--text_box
        .ranking__contents--contents_box--text_box--name
          名前：しょーきちさん
        .ranking__contents--contents_box--text_box--likes
          いいね！：220
    .ranking__contents--text
      %h1.no1 No.2
    .ranking__contents--contents_box
      = link_to "#"
      .ranking__contents--contents_box--image
        = image_tag 'top_cat.jpg',height: '100', width: '100',class:"mini_image"
      .ranking__contents--contents_box--text_box
        .ranking__contents--contents_box--text_box--name
          名前：しょーきちさん
        .ranking__contents--contents_box--text_box--likes
          いいね！：220

app/views/cat/new.html.haml
.new
  .new__main
    = form_with model: @cat, local: true do |form|
      .new__main__text
        %h1.text30 猫ちゃんを投稿してください
      .new__main__image_post
      .new__main__info_box
        .new__main__info_box--name_text
          %h1.text31 猫ちゃんの名前
          .new__main__info_box--name_box
            = form.text_field :name, placeholder: "例）みーちゃん"
        .new__main__info_box--gender_living
          .new__main__info_box--gender_living--gender
            %h3.text32 性別
            .new__main__info_box--gender_living--gender__chack1
              =check_box_tag :check1 do
                =label_tag :check1, "オス"
            .new__main__info_box--gender_living--gender__chack2
              =check_box_tag :check2 do
                =label_tag :check2, "メス"
          .new__main__info_box--gender_living--living
            生息地
            .new__main__info_box--gender_living--living__box
              %select.lives_input
        .new__main__info_box--color
          %h3.text34_color 毛色
          .new__main__info_box--color__input
            %select.color_input
        .new__main__info_box--features
          = form_with model: @comment, local: true do |form|
            %h3.text35 特徴
            .new__main__info_box--features__input_box
              = form.text_area :name, placeholder: "例）おとなしい性格です。車の上でひなたぼっこしています。"
    .new__submit
      .new__submit__box
        %input.send{:type => "submit", :value => "登録する"}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ootaneko</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/toppage/_header.html.haml
%header
  .header__search_box
    .header__search_box__input
      = link_to "#" do
        .header__search_box__input__icon
          %i.fas.fa-search
  .header__tabs_box
    .header__tabs_box__area
      = link_to "地域で探す","#"
    .header__tabs_box__color
      = link_to "毛色で探す","#"
    .header__tabs_box__likes
      = link_to "いいねランキング",cat_index_path

    - if user_signed_in?
      .header__tabs_box__newPost
        = link_to "新規投稿",new_cat_path
      .header__tabs_box__logOut
        = link_to "ログアウト",destroy_user_session_path,method: :delete
    - else
      .header__tabs_box__login
        = link_to "ログイン",new_user_session_path
      .header__tabs_box__singup
        = link_to "新規登録",new_user_registration_path

app/views/toppage/index.html.haml
.main
  = render "header"
  .contents
    .contents__image
      %h1　ようこそ地域猫登録アプリへ！
    .contents__main
      %h3.contents__main__text
        人気ランキング
      .contents__main__contents_box
        .contents__main__contents_box__content
          .contents__main__contents_box__content__text
            いいね数１位
          .contents__main__contents_box__content__info
            =link_to "#"
            .contents__main__contents_box__content__info--image
              = image_tag 'top_cat.jpg',height: '188', width: '272', class: 'mini_cat'
              .contents__main__contents_box__content__info--image__name
                名前:みいちゃん
            .contents__main__contents_box__content__info--text
              地域:蒲田　    
              %br毛色:トラ柄
              特徴:人懐っこい
        .contents__main__contents_box__content
          .contents__main__contents_box__content__text
            いいね数２位
          .contents__main__contents_box__content__info
            =link_to "#"
            .contents__main__contents_box__content__info--image
              = image_tag 'top_cat.jpg',height: '188', width: '272', class: 'mini_cat'
              .contents__main__contents_box__content__info--image__name
                名前:たけお
            .contents__main__contents_box__content__info--text
              地域:蒲田
              %br毛色:トラ柄
              特徴:人懐っこい

      %h3.contents__main__text
        新入り猫
      .contents__main__contents_box
        .contents__main__contents_box__content
          .contents__main__contents_box__content__text
            2020年2月10日に追加されました
          .contents__main__contents_box__content__info
            =link_to "#"
            .contents__main__contents_box__content__info--image
              = image_tag 'top_cat.jpg',height: '188', width: '272', class: 'mini_cat'
              .contents__main__contents_box__content__info--image__name
                名前:みいちゃん
            .contents__main__contents_box__content__info--text
              地域:蒲田
              %br毛色:トラ柄
              特徴:人懐っこい

      %h3.contents__main__text
        迷い猫情報！
      .contents__main__contents_box
        .contents__main__contents_box__content
          .contents__main__contents_box__content__text
            いいね数１位
          .contents__main__contents_box__content__info
            =link_to "#"
            .contents__main__contents_box__content__info--image
              = image_tag 'top_cat.jpg',height: '188', width: '272', class: 'mini_cat'
              .contents__main__contents_box__content__info--image__name
                名前:みいちゃん
            .contents__main__contents_box__content__info--text
              地域:蒲田
              %br毛色:トラ柄
              特徴:人懐っこい
              

app/views/toppage/show.html.haml
.show
  = render "toppage/header"
  .show__contents
    .show__contents__text
      .show__contents__text--create
        発見日：2020/02/02
      .show__contents__text--living
        生息場所：蒲田
    .show__contents--images
      .show__contents--images__image
        = image_tag 'top_cat.jpg',height: '500', width: '1000',class:"image"
    .show__contents--info
      .show__contents--info__text
        %h1　猫ちゃんの詳細情報
      .show__contents--info__details
        .show__contents--info__details--likes
          %h3 いいね：220
        .show__contents--info__details--name
          %br名前：しょーきちさん
        .show__contents--info__details--gender
          %br性別：オス
        .show__contents--info__details--color
          %br毛色：サバトラ
        .show__contents--info__details--comment
          %br特徴：おとなしい性格です。結構人懐っこいです。よく近所の車の上で日向ぼっこしています。
    .show__contents--coment_box
      %h1.text1　コメント
      .show__contents--coment_box__content
        .show__contents--coment_box__content--name_box
          .show__contents--coment_box__content--name_box__nickname
            投稿者：たけぽん
          .show__contents--coment_box__content--name_box__time
            投稿時間：2020/02/03
        .show__contents--coment_box__content--coment
          かわいい
      .show__contents--coment_box__content
        .show__contents--coment_box__content--name_box
          .show__contents--coment_box__content--name_box__nickname
            投稿者：たけぽん
          .show__contents--coment_box__content--name_box__time
            投稿時間：2020/02/03
        .show__contents--coment_box__content--coment
          かわいい